# Análisis de componentes principales



*Carlos Isaac Zainea Maya*

**Universidad Central**

## Introducción




> * El análisis en componentes principales es una técnica de análisis estadístico multivariante que se clasifica entre los métodos de simplificación o reducción de la dimensión. Se aplica cuando se dispone de un conjunto elevado de variables y busca reescribir los valores a partir de combinaciones lineales que se denominan componentes principales o factores.
>
> *  Es un método que permite describir, de un modo
sintético, la estructura y las interrelaciones de las variables originales en el fenómeno que se estudia a partir de las componentes obtenidas que, naturalmente, habrá que interpretar y «nombrar».
>
>* La reducción de variables a pocas componentes puede simplificar la aplicación sobre otras técnicas multivariantes (regresión, clusters, etc.)

Obtenemos las componentes principales a partir de la matriz de covarianzas o correlaciones y sus valores y vectores propios. Como dicha matriz es semidefinida positiva grantizamos la nonegatividad de los valores propios. Los organizamos de mayor a menor para definir el orden de los componentes.



## Objetivo operativo del ACP

* Describir la variación de un conjunto de variables correlacionadas, $x^T=(x_1,x_2,\cdots,x_q)$ en  términos de unas nuevas variables NO correlacionadas, $y^T=(y_1,y_2,\cdots,y_q)$, las cuales sean combinaciones lineales de las variables $x$.



Para lograr este objetivo iniciamos tipificando las variables, es decir, hacemos una transformación simple que produzca unas nuevas variables $Z_i$ con media $0$ y desviación estándar $1$. 

Lo hacemos porque, buscamos una matriz $U$ de $q\times q$ tal que:

$Y=Z\cdot U$

con $Z$ la matriz de todas las observaciones tipificadas.



**Pregunta** 

Si $Z$ es la matriz $n\times q$ que contiene todas las observaciones tipificadas ¿Qué puede decir de la matriz $Z^T Z$ de tamaño $q\times q$?

**Ejemplo**

Tipificaremos las variables cuantitativas de la superconocida base `iris`.

In [1]:
import pandas as pd
import numpy as np
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url, names=['sepal length','sepal width','petal length','petal width','target'])

In [2]:
df.describe()

sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [3]:
from sklearn.preprocessing import StandardScaler

features = ['sepal length', 'sepal width', 'petal length', 'petal width']

x = df.loc[:, features].values
x #la matriz que contiene a todas las observaciones

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = df.loc[:,['target']].values
y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [5]:
x2 = StandardScaler(with_std=False).fit_transform(x)
#x2 = StandardScaler().fit_transform(x)

In [6]:
standardbase=pd.DataFrame(x2, columns=['sepal length','sepal width','petal length','petal width'])

In [7]:
standardbase.head()

sepal length  sepal width  petal length  petal width
0     -0.743333        0.446     -2.358667    -0.998667
1     -0.943333       -0.054     -2.358667    -0.998667
2     -1.143333        0.146     -2.458667    -0.998667
3     -1.243333        0.046     -2.258667    -0.998667
4     -0.843333        0.546     -2.358667    -0.998667

In [8]:
PromC1=df["sepal length"].mean()
DevestC1=np.std(df["sepal length"])
print(PromC1)
print(DevestC1)

5.843333333333335
0.8253012917851409


In [9]:
estandarización=lambda x:(x-PromC1)

In [10]:
df["sepal length"].apply(estandarización)

0     -0.743333
1     -0.943333
2     -1.143333
3     -1.243333
4     -0.843333
         ...   
145    0.856667
146    0.456667
147    0.656667
148    0.356667
149    0.056667
Name: sepal length, Length: 150, dtype: float64

In [18]:
0.36*standardbase["sepal length"]-0.08226889*standardbase["sepal width"]+0.85657211*standardbase["petal length"]+ 0.35884393*standardbase["petal width"]

0     -2.683025
1     -2.713891
2     -2.888002
3     -2.744461
4     -2.727252
         ...   
145    1.942655
146    1.524938
147    1.763002
148    1.901062
149    1.389576
Length: 150, dtype: float64

Respuesta a las preguntas anteriores:

In [ ]:
x2

In [13]:
np.dot(np.transpose(x2),(x2))*(1/149)

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [14]:
np.cov(np.transpose(x))

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [15]:
COV=np.cov(np.transpose(x))

In [ ]:
import matplotlib.pyplot as plt 
import seaborn as sns
fig, ax = plt.subplots()
s=sns.heatmap(df.iloc[:,0:4].corr(),cmap='coolwarm') 
s.set_yticklabels(s.get_yticklabels(),rotation=30,fontsize=7)
s.set_xticklabels(s.get_xticklabels(),rotation=30,fontsize=7)
ax.set_xlim(0,4)
ax.set_ylim(0,4)
plt.show()

In [ ]:
df.iloc[:,0:4].cov()

In [19]:
import matplotlib.pyplot as plt 
import seaborn as sns
fig, ax = plt.subplots()
s=sns.heatmap(df.iloc[:,0:4].cov(),cmap='coolwarm', center=0,
             linewidths=.5, cbar_kws={"shrink": .5},annot=True) 
s.set_yticklabels(s.get_yticklabels(),rotation=30,fontsize=7)
s.set_xticklabels(s.get_xticklabels(),rotation=30,fontsize=7)
ax.set_xlim(0,4)
ax.set_ylim(0,4)
plt.show()

<Figure size 640x480 with 2 Axes>

## Volvamos al problema

Como se comentó, tenemos que calcular una matriz $U$ para hacer la transformación de $X$ a $Y$. Sin embargo, hay que cumplir algunas condiciones:

1. Primero deben aparecer variables que representen la mayor varianza de las variables $X$.

2. No puede haber correlación entre las variables en $Y$.

Con esta información iniciemos el calculo de cada variable en $Y$, las llamaremos componentes:

$$\begin{bmatrix}Y_{11}\\Y_{12}\\\vdots \\Y_{1n}\end{bmatrix}=\begin{bmatrix}X_{11}& X_{21}& \cdots&X_{q1}\\X_{12}& X_{22}& \cdots&X_{q2}\\\vdots& \vdots &\ddots&\vdots\\ X_{1n}& X_{2n}& \cdots&X_{qn}\end{bmatrix}\begin{bmatrix}u_{11}\\u_{12}\\\vdots \\u_{1q}\end{bmatrix}$$




**Cálculo de la primera componente y Varianza Maxima:**

Calcular la varianza de la primera componente equivale a:
$$V(Y_1)=\frac{1}{n}Y^T\cdot Y=\frac{1}{n}u_1^TX^TXu_1=u_1^TVu_1$$

Luego, debemos maximizar:
$$V(Y_1)=u_1^TVu_1$$ sujeto a $u^Tu=1$.

Es un problema de Lagrange, tenemos:

$$L=u_1^TVu_1-\lambda(u_1^Tu_1-1)$$

Derivando llegamos a:

$$(V-\lambda I)u_1=0$$

Que es un problema de valores y vectores propios.


## El cálculo de componentes

In [16]:
np.linalg.eig(COV)

(array([4.22484077, 0.24224357, 0.07852391, 0.02368303]),
 array([[ 0.36158968, -0.65653988, -0.58099728,  0.31725455],
        [-0.08226889, -0.72971237,  0.59641809, -0.32409435],
        [ 0.85657211,  0.1757674 ,  0.07252408, -0.47971899],
        [ 0.35884393,  0.07470647,  0.54906091,  0.75112056]]))

## Cálculo de componentes

In [20]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2', 'principal component 3', 'principal component 4'])

In [23]:
principalDf

principal component 1  principal component 2  principal component 3  \
0                -2.684207               0.326607              -0.021512   
1                -2.715391              -0.169557              -0.203521   
2                -2.889820              -0.137346               0.024709   
3                -2.746437              -0.311124               0.037672   
4                -2.728593               0.333925               0.096230   
..                     ...                    ...                    ...   
145               1.944017               0.187415               0.179303   
146               1.525664              -0.375021              -0.120636   
147               1.764046               0.078519               0.130784   
148               1.901629               0.115877               0.722874   
149               1.389666              -0.282887               0.362318   

     principal component 4  
0                 0.001006  
1                 0.099602  
2                 0.019305  
3                -0.075955  
4                -0.063129  
..                     ...  
145               0.425082  
146               0.255723  
147               0.136295  
148               0.040873  
149              -0.156310  

[150 rows x 4 columns]

In [22]:
finalDf = pd.concat([principalDf, df[['target']]], axis = 1)

## Visualización en Python



In [ ]:
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_zlabel('Principal Component 3', fontsize = 15)
ax.set_title('3 component PCA', fontsize = 20)
targets = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
colors = ['r', 'g', 'b']
for target, color in zip(targets,colors):
    indicesToKeep = finalDf['target'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
               , finalDf.loc[indicesToKeep, 'principal component 2']
               , finalDf.loc[indicesToKeep, 'principal component 3']
               , c = color
               , s = 50)
ax.legend(targets)
ax.grid()

In [ ]:
pca.explained_variance_ratio_